# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself

# 自动更新 fastlane
# update_fastlane

default_platform(:ios)

platform :ios do
  
  before_all do
    #cocoapods
  end

  desc "发布到应用商店苹果商店"
  lane :release_apple do
    gym(scheme: ENV['SCHEME_NAME'],
      silent: true,  
      export_method:"app-store",
      buildlog_path:"fastlanelog",
      output_directory:"build",
      clean: true  
    )
    deliver
    review_time(platform: "iOS")
  end

  desc "导出发布版iPA"
  lane :export_IPA do
    gym(scheme: ENV['SCHEME_NAME'],
      silent: true,  
      export_method:"app-store",
      buildlog_path:"fastlanelog",
      output_directory:"build",
      clean: true 
    )


  end

  desc "导出开发环境iPA"
  lane :export_Ad_Hoc_IPA do
    gym(scheme: ENV['SCHEME_NAME'],
      silent: true,  
      export_method:"ad-hoc",
      buildlog_path:"fastlanelog",
      output_directory:"build",
      clean: true  
    )
    
  end

  desc "获取开发证书和配置文件"
  lane :getDevCert do
    #register_devices(devices_file: "./fastlane/multiple-device-upload-ios.txt")
    # sh "fastlane match nuke development -force"
    match(
      git_branch: "glance",
      type: 'appstore',
      #readonly: 'true',
      profile_name: 'Glance_test_appstore',
      verbose: true
    )
  end



  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: 'Glance.xcodeproj')
    build_app(workspace: "Glance.xcworkspace",
      clean: true ,
      scheme: ENV['SCHEME_NAME'],
      export_method:'app-store',
      include_bitcode: false,
      buildlog_path:"fastlanelog",
      output_directory:"build",
      export_options: {
      provisioningProfiles: {
        "com.belive.glance-p"=>"Glance_prerelease_appstore"
      }
    })
    upload_to_testflight(
      skip_waiting_for_build_processing: false)

  end



end
